responses:
  1XX:
    description: 서버가 요청을 받았으니 나머지 프로세스를 계속 진행하세요.
  2XX:
    description: 서버가 요청을 성공적으로 받았으며 수행했습니다.
  3XX:
    description: 서버의 요청 완료를 위해 추가 작업이 필요합니다.
  4XX:
    description: 서버에 요청한 문법이 잘못되었거나 처리할 수 없습니다.
  5XX:
    description: 서버가 명백히 유효한 요청에 대한 충족을 실패했습니다.