openapi: 3.0.0
info: 
  title: My API
  version: 1.0.0
  description: API-DOCUMENTS

tags: 
  name: Auth
  description: Auth restful

paths:
  $ref: '../swagger/auth.yaml'

components:
  $ref: '../swagger/components.yaml'