openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API-DOCUMENTS
tags:
  name: Auth
  description: Auth restful
paths:
  /auth/users:
    post:
      tags:
        - Auth
      summary: 유저 생성
      requestBody:
        required:
          - id
          - password
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              example:
                id: test123@test.com(이메일 형식)
                password: '@Asd456456546(특수문자, 대문자, 소문자 1개이상 포함 + 10자 이상)'
      responses:
        1XX(정보):
          $ref: '#/components/responses/1XX'
        2XX(성공):
          $ref: '#/components/responses/2XX'
        3XX(리다이렉션):
          $ref: '#/components/responses/3XX'
        4XX(클라이언트 오류):
          $ref: '#/components/responses/4XX'
        5XX(서버 오류):
          $ref: '#/components/responses/5XX'
  /auth/users/status:
    post:
      tags:
        - Auth
      summary: 유저 로그인
      requestBody:
        required:
          - id
          - password
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              example:
                id: test123@test.com
                password: '@Asd456456546'
      responses:
        1XX(정보):
          $ref: '#/components/responses/1XX'
        2XX(성공):
          $ref: '#/components/responses/2XX'
        3XX(리다이렉션):
          $ref: '#/components/responses/3XX'
        4XX(클라이언트 오류):
          $ref: '#/components/responses/4XX'
        5XX(서버 오류):
          $ref: '#/components/responses/5XX'
components:
  responses:
    1XX:
      description: 서버가 요청을 받았으니 나머지 프로세스를 계속 진행하세요.
    2XX:
      description: 서버가 요청을 성공적으로 받았으며 수행했습니다.
    3XX:
      description: 서버의 요청 완료를 위해 추가 작업이 필요합니다.
    4XX:
      description: 서버에 요청한 문법이 잘못되었거나 처리할 수 없습니다.
    5XX:
      description: 서버가 명백히 유효한 요청에 대한 충족을 실패했습니다.
